version: '3.7'
services:
  ytdl:
    container_name: ytdl
    image: povoma4617/ytdlbot:latest
    environment:
      # - APP_ID=
      # - APP_HASH=
      # - TOKEN=
      OWNER: "number"
      AUTHORIZED_USER: "number"
      ENABLE_ARIA2: "True"
      PREMIUM: "True"
      ENABLE_FFMPEG: "True"
      TWITTER_COOKIES: "/app/conf/twitter_cookies.txt"
      X_COM_COOKIES: "/app/conf/twitter_cookies.txt" 
      INSTAGRAM_COOKIES: "/app/conf/instagram_cookies.txt"
      YOUTUBE_COOKIES: "/app/conf/youtube_cookies.txt"
      YOUTU_BE_COOKIES: "/app/conf/youtube_cookies.txt"
      BILIBILI_COOKIES: "/app/conf/bilibili_cookies.txt" 
      B23_COOKIES: "/app/conf/bilibili_cookies.txt"
    volumes:
      - /path/to/cookies:/app/conf # twitter_cookies.txt and instagram_cookies.txt
      - /path/to/docker-session/my_account.session:/ytdlbot/ytdlbot/my_account.session
      - /path/to/docker-session/ytdl-main.session:/ytdlbot/ytdlbot/ytdl-main.session
    restart: always
