version: '3.7'
services:
  ytdl:
    container_name: ytdl
    image: povoma4617/ytdlbot:latest
    environment:
      # - APP_ID=
      # - APP_HASH=
      # - TOKEN=
      - OWNER=
      - AUTHORIZED_USER=
      - ENABLE_ARIA2=True 
      - PREMIUM=True # premium can upload videos larger than 2GB
    volumes:
      - /path/to/cookies:/app/conf # twitter_cookies.txt and instagram_cookies.txt
      - /path/to/docker-session/my_account.session:/ytdlbot/ytdlbot/my_account.session
      - /path/to/docker-session/ytdl-main.session:/ytdlbot/ytdlbot/ytdl-main.session
    restart: always
